const STRINGS = {
  app: {
    brand: 'Admin Panel',
    searchPlaceholder: 'Search...',
    overview: 'Overview',
    signedInAs: 'Signed in as',
    logout: 'Logout',
  },
  nav: {
    dashboard: 'Dashboard',
    patientRegistration: 'Patient Registration',
    settings: 'Settings',
    users: 'Users',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Key metrics and quick actions',
    export: 'Export',
    newPatient: 'New Patient',
    kpi: {
      totalPatients: 'Total Patients',
      registrationsToday: 'Registrations Today',
      pendingReviews: 'Pending Reviews',
      appointments: 'Appointments',
      reviewRequired: 'Review required',
      nextIn: 'Next in 12 min',
    },
    chartTitle: 'Registrations (Last 7 days)',
    range7d: '7d',
    range30d: '30d',
    range90d: '90d',
    recentActivity: 'Recent Activity',
  },
  patient: {
    title: 'Patient Registration',
    subtitle: 'Add a new patient to the system',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    dateOfBirth: 'Date of Birth',
    registerBtn: 'Register Patient',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Manage application and profile settings',
    profile: 'Profile',
    fullName: 'Full Name',
    email: 'Email',
    saveChanges: 'Save Changes',
    preferences: 'Preferences',
    notif: 'Enable email notifications',
    darkMode: 'Dark mode (coming soon)',
  },
  roles: {
    permissionsHeader: 'Roles',
    editPermissions: 'Edit Permissions',
    viewHistory: 'View History',
    save: 'Save',
    cancel: 'Cancel',
    roles: 'Roles',
    addRole: 'Add Role',
    noAddPermission: 'You do not have Add Permission',
    addRoleTooltip: 'Add Role',
    type: 'TYPE',
    actionHeader: 'Action',
    noRolesFound: 'No roles found',
    editingBanner: 'You are editing permissions',
    toggleAll: 'Toggle all',
    enableAll: 'Enable all',
    disableAll: 'Disable all',
    deleteRoleTitle: 'Delete Role',
    deleteRoleConfirm: 'Are you sure you want to delete',
    deleteRoleImpact: 'This action will permanently delete this role and all the users assigned with this Role.',
    deleteRoleIrreversible: 'This operation can not be undone.',
    yes: 'Yes',
    create: 'Create',
    newRoleName: 'New Role Name :',
    roleName: 'Role Name :',
    saveChangesShort: 'Save',
    modalClose: 'Cancel',
    editRoleName: 'Edit Role Name',
    selectRoleTooltip: 'Select a Role',
  },
}

export default STRINGS


